# Site settings
title: Transitland
email: hello@transit.land
description: >
  A community-edited data service aggregating transit networks
  across metropolitan and rural areas around the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://transit.land" # the base hostname & protocol for your site

future: true # show posts with future dates, rather than using drafts

plugins:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
exclude:
  - vendor
  - Rakefile
  - Gemfile
  - .*
  - circle.yml
  - README.md
  - config/
  - lib/
  - deploy/
